baseurl: "http://yoursite.example.com/"
permalinks:
  posts: /:year/:month/:title/
  about: /:title/
  contact: /:title/
paginate: 6
params:
  googleAnalyticsId: UA-72716434-1
sitemap:
  changefreq: "weekly"
  priority: 0.5
LanguageCode: fr-fr
